apiVersion: v1
kind: Pod
metadata:
  name: py-docker-pod
spec:
  containers:
    - name: py-docker
      image: roneigualberto/py-docker
      resources:
        requests:
          cpu: 100m
          memory: 128M
        limits:
          cpu: 250m
          memory: 256M
      ports: 
        - containerPort: 5000